spring:
  application:
    name: tend-calculator
  output:
    ansi:
      enabled: ALWAYS
  main:
    banner-mode: off
    log-startup-info: false

logging:
  level:
    root: warn
    org.springframework: warn

cli:
  enabled: true